# This is a basic workflow to help you get started with Actions

name: SB Engine workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BuildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


  BuildAndroid:
    name: BuildAndroid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib --quiet install hxcpp 4.2.1 > /dev/null
          haxelib --quiet install lime 8.0.2
          haxelib --quiet install openfl 9.2.1
          haxelib --quiet install flixel
          haxelib --quiet run lime setup flixel
          haxelib --quiet install flixel-tools
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons
          haxelib --quiet install tjson
          haxelib --quiet install hxjsonast
          haxelib --quiet install hscript
          haxelib --quiet git SScript https://github.com/Fearester2008/SScript
          haxelib --quiet git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib --quiet git linc_luajit https://github.com/PsychExtendedThings/linc_luajit.git
          haxelib --quiet git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib --quiet git AndroidDialogs https://github.com/beihu235/AndroidDialogs
          haxelib --quiet git devicelanguage https://github.com/beihu235/devicelanguage
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 8.0.2
          haxelib set openfl 9.2.1
          haxelib set hxcpp 4.2.1
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: SB Engine Android build
          path: export/release/android/bin/app/build/outputs/apk/debug
